# Generated by Django 5.2.8 on 2025-11-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, help_text='Brief summary of the book', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='Title of the book', max_length=200, unique=True),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_book_title', violation_error_message='A book with this title already exists.'),
        ),
    ]
